# Generated by Django 3.2.7 on 2021-09-29 23:21

from django.db import migrations, models
import django.db.models.deletion
import validators.string_validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('zip_code', models.CharField(default='Unknown', max_length=10)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(default='Unknown', max_length=50)),
                ('coordinates', models.CharField(default=None, max_length=12)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('wiki_url', models.CharField(default='Unknown', max_length=100)),
                ('region', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.region')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30, validators=[validators.string_validation.no_naughty_words])),
                ('last_name', models.CharField(max_length=30, validators=[validators.string_validation.no_naughty_words])),
                ('location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.location')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
